---

- name: set force install fact
  set_fact:
    force: "{{ force | default('false')  }}"
    solana_bin_path: "{{ solana_app_path }}"
  tags:
    - cli
    - cli.install
    - cli.update

- name: Load config
  include_vars:
    file: "{{ sv_manager_config_path }}"
  become: yes

- name: check solana cli installed
  stat:
    path: "{{ solana_bin_path }}/releases/{% if solana_version is defined %}{{ solana_version }}{% else %}stable{% endif %}/solana_release/bin/agave-install"
  register: solana_exists
  tags:
    - cli
    - cli.install
    - cli.update

- name: install solana cli
  import_tasks: install.yaml
  tags:
    - cli
    - cli.install
  when: force == 'true' or not solana_exists.stat.exists

- name: update solana cli
  import_tasks: update.yaml
  tags:
    - cli
    - cli.update
  when: force != 'true' and solana_exists.stat.exists

- name: install solana-snapshot-finder
  import_tasks: solana_snapshot_finder.yaml
  tags:
    - cli
    - cli.snapshot-finder
  when: with_snapshot_finder

#- name: "Add {{ solana_bin_path }}/active_release/bin to PATH if does not exist"
#  lineinfile:
#    path: /etc/environment
#    line: 'PATH="$PATH:{{ solana_bin_path }}/active_release/bin"'
#    insertafter: EOF
#  when: lookup('file', '/etc/environment') is not search('^\s*PATH\s*=')
#
#- name: 'Add {{ solana_bin_path }}/active_release/bin to PATH'
#  lineinfile:
#    path: /etc/environment
#    regexp: 'PATH=(["])((?!.*?{{ solana_bin_path }}/active_release/bin).*?)(["])$'
#    line: 'PATH=\1\2:{{ solana_bin_path }}/active_release/bin\3'
#    backrefs: yes